Controllers/BookingController.cs
using Microsoft.AspNetCore.Mvc;
using Progetto_Settimanale_Vescio_Pia_Francesca.Models;
using Progetto_Settimanale_Vescio_Pia_Francesca.Services.Data;
using Progetto_Settimanale_Vescio_Pia_Francesca.Services.Interfaces;
using Progetto_Settimanale_Vescio_Pia_Francesca.DAO.Data;
using Microsoft.AspNetCore.Authorization;
namespace Progetto_Settimanale_Vescio_Pia_Francesca.Controllers
{
    [Authorize]
    public class BookingController : Controller
    {
        private readonly IBookingService _bookingService;

        public BookingController(IBookingService bookingService)
        {
            _bookingService = bookingService;
        }
        public IActionResult AllBooking()
        {
            var booking = _bookingService.GetAll();
            var bookingModels = booking.Select(b => new BookingModel
            {
                Id = b.Id,
                DateBooking = b.DateBooking,
                YearProg = b.YearProg,
                DateStart = b.DateStart,
                DateEnd = b.DateEnd,
                Deposit = b.Deposit,
                Rate = b.Rate,
                TypeofStay = b.TypeofStay,
                Customer = new CustomerModel
                {
                    Id = b.Customer.Id,
                    LastName = b.Customer.LastName,
                    FirstName = b.Customer.FirstName,
                    City = b.Customer.City,
                    Province = b.Customer.Province,
                    Email = b.Customer.Email,
                    Telephone = b.Customer.Telephone,
                    MobilePhone = b.Customer.MobilePhone,
                    FiscalCode = b.Customer.FiscalCode
                },
                Room = new RoomModel
                {
                    Id = b.Room.Id,
                    NumberRoom = b.Room.NumberRoom,
                    TypeofRoom = b.Room.TypeofRoom,
                    
                }
            }).ToList();
            return View(bookingModels);
        }
        
        public IActionResult RegisterBooking()
        {
            return View(new BookingModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RegisterBooking(BookingModel booking) 
        { 
                _bookingService.Create(
                    new BookingDto
                    {
                        Id = booking.Id,
                        DateBooking = booking.DateBooking,
                        YearProg = booking.YearProg,
                        DateStart = booking.DateStart,
                        DateEnd = booking.DateEnd,
                        Deposit = booking.Deposit,
                        Rate = booking.Rate,
                        TypeofStay = booking.TypeofStay,
                        Customer = new CustomerEntity
                        {
                            Id = booking.Customer.Id,
                        },
                        Room = new RoomEntity
                        {
                            Id = booking.Room.Id,
                        }

                    });
                return RedirectToAction("AllBooking", "Booking");
        }

        public IActionResult Update(int id)
        {
            var booking = _bookingService.Read(id);
            var bookingModel = new BookingModel
            {

                Id = booking.Id,
                DateBooking = booking.DateBooking,
                YearProg = booking.YearProg,
                DateStart = booking.DateStart,
                DateEnd = booking.DateEnd,
                Deposit = booking.Deposit,
                Rate = booking.Rate,
                TypeofStay = booking.TypeofStay,
                Customer = new CustomerModel
                {
                    Id = booking.Customer.Id,
                },
                Room = new RoomModel
                {
                    Id = booking.Room.Id,
                }
            };
            return View(bookingModel); 
        }

        [HttpPost]
        public IActionResult Update(int id, BookingModel booking)
        {
            var b = _bookingService.Update(id, new BookingDto
            {
                Id = booking.Id,
                DateBooking = booking.DateBooking,
                YearProg = booking.YearProg,
                DateStart = booking.DateStart,
                DateEnd = booking.DateEnd,
                Deposit = booking.Deposit,
                Rate = booking.Rate,
                TypeofStay = booking.TypeofStay,
                Customer = new CustomerEntity
                {
                    Id = booking.Customer.Id,
                },
                Room = new RoomEntity
                {
                    Id = booking.Room.Id,
                }
            });
            return RedirectToAction("AllBooking", "Booking");
        }
        public IActionResult DeleteBooking(int id)
        {
            _bookingService.Delete(id);
            return RedirectToAction("AllBooking", "Booking");
        }
    }

}

Controllers/CheckOutController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Progetto_Settimanale_Vescio_Pia_Francesca.Models;
using Progetto_Settimanale_Vescio_Pia_Francesca.Services.Interfaces;

namespace Progetto_Settimanale_Vescio_Pia_Francesca.Controllers
{
    [Authorize]
    public class CheckOutController : Controller
    {
        public readonly ICheckOutService _checkoutService;
        public CheckOutController(ICheckOutService checkOutService) 
        {
            _checkoutService = checkOutService;
        }
        public IActionResult Checkout(int id)
        {   
            TotalCheckOut totalCheckOut = new TotalCheckOut();
            totalCheckOut.NameCustomer = _checkoutService.NameOfCostumer(id);
            totalCheckOut.RoomofCustomer = _checkoutService.RoomofCustomer(id);
            totalCheckOut.TolalAdditionalService = _checkoutService.TolalAdditionalService(id);
            totalCheckOut.TotalToPay = _checkoutService.TotalToPay(id);

            return View(totalCheckOut);
        }
    }
}

Views/Booking/AllBooking.cshtml
@model IEnumerable<Progetto_Settimanale_Vescio_Pia_Francesca.Models.BookingModel>

@{
    ViewData["Title"] = "AllBooking";
}

<h1>AllBooking</h1>

<p>
    <a class="btn btn-primary btn-sm" asp-action="RegisterBooking" asp-action="Booking">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateBooking)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.YearProg)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateStart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateEnd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deposit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TypeofStay)
            </th>
            <th>
                Cliente
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Room.NumberRoom)
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateBooking)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YearProg)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.DateStart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateEnd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deposit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypeofStay)
            </td>
            <td>
                @item.Customer.LastName @item.Customer.FirstName
            </td>
                <td>
                   @Html.DisplayFor(modelItem => item.Room.NumberRoom)
                </td>
            <td>
                    <a class="btn btn-primary btn-sm" asp-controller="CheckOut" asp-action="Checkout" asp-route-id="@item.Id" class="btn btn-primary">Checkout</a>
                    <a class="btn btn-primary btn-sm" asp-controller="Booking" asp-action="Update" asp-route-id="@item.Id" class="btn btn-primary">Modifica</a>
                    <a class="btn btn-primary btn-sm mt-1" asp-controller="Booking" asp-action="DeleteBooking" asp-route-id="@item.Id" class="btn btn-primary">Elemina</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Booking/RegisterBooking.cshtml
@model Progetto_Settimanale_Vescio_Pia_Francesca.Models.BookingModel

@{
    ViewData["Title"] = "RegisterBooking";
}

<h1>RegisterBooking</h1>

<h4>BookingModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="RegisterBooking">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DateBooking" class="control-label"></label>
                <input asp-for="DateBooking" class="form-control" />
                <span asp-validation-for="DateBooking" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearProg" class="control-label"></label>
                <input asp-for="YearProg" class="form-control" />
                <span asp-validation-for="YearProg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateStart" class="control-label"></label>
                <input asp-for="DateStart" class="form-control" />
                <span asp-validation-for="DateStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEnd" class="control-label"></label>
                <input asp-for="DateEnd" class="form-control" />
                <span asp-validation-for="DateEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deposit" class="control-label"></label>
                <input asp-for="Deposit" class="form-control" />
                <span asp-validation-for="Deposit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rate" class="control-label"></label>
                <input asp-for="Rate" class="form-control" />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeofStay" class="control-label"></label>
                <input asp-for="TypeofStay" class="form-control" />
                <span asp-validation-for="TypeofStay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer" class="control-label"></label>
                <select asp-for="Customer.Id" id="customer">
                
                </select>
            </div>
            <div>
                <label asp-for="Room" class="control-label"></label>
                <select asp-for="Room.Id" id="room">
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Booking/Update.cshtml
@model Progetto_Settimanale_Vescio_Pia_Francesca.Models.BookingModel

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>BookingModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateBooking" class="control-label"></label>
                <input asp-for="DateBooking" class="form-control" />
                <span asp-validation-for="DateBooking" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearProg" class="control-label"></label>
                <input asp-for="YearProg" class="form-control" />
                <span asp-validation-for="YearProg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateStart" class="control-label"></label>
                <input asp-for="DateStart" class="form-control" />
                <span asp-validation-for="DateStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEnd" class="control-label"></label>
                <input asp-for="DateEnd" class="form-control" />
                <span asp-validation-for="DateEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deposit" class="control-label"></label>
                <input asp-for="Deposit" class="form-control" />
                <span asp-validation-for="Deposit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rate" class="control-label"></label>
                <input asp-for="Rate" class="form-control" />
                <span asp-validation-for="Rate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeofStay" class="control-label"></label>
                <input asp-for="TypeofStay" class="form-control" />
                <span asp-validation-for="TypeofStay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer" class="control-label"></label>
                <select asp-for="Customer.Id" id="customer">
                </select>
            </div>
            <div>
                <label asp-for="Room" class="control-label"></label>
                <select asp-for="Room.Id" id="room">
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>